FROM python:3

COPY ./requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

RUN rm -rf /prereqs

COPY . /netutils
WORKDIR /netutils

CMD ["python3", "setup.py", "bdist_wheel", "-d", "/tmp/dist/"]
