@startuml

languages: language_id [UUID]
languages: title [UUID]

system: system_id [UUID]
system: title [TEXT]
system: native_language_id [UUID]
system: foreign_language_id [UUID]
system -> languages: native, foreign

categories: category_id [UUID]
categories: system_id [UUID]
categories: title [TEXT]
categories --> system

training: training_id [UUID]
training: category_id [UUID]
training: native_word [TEXT]
training: foreign_word [TEXT]
training --> categories

@enduml