CREATE OR REPLACE FUNCTION get_training_by_id(
    p_training_id UUID
)

RETURNS TABLE(training_id UUID,
              category_id UUID,
              native_word TEXT,
              foreign_word TEXT)
AS
$BODY$
  BEGIN
    RETURN QUERY
    SELECT t.training_id, t.category_id, t.native_word, t.foreign_word
    FROM training t
    WHERE t.training_id = p_training_id;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;
