CREATE OR REPLACE FUNCTION get_text_by_translation(
    p_translation TEXT
)

RETURNS TABLE(training_id UUID,
              category_id UUID,
              native_word TEXT,
              foreign_word TEXT)
AS
$BODY$
  BEGIN
    RETURN QUERY
    SELECT t.training_id, t.category_id, t.native_word, t.foreign_word
    FROM training t
    WHERE t.native_word = p_translation;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;
