version: "3"
services:

  postgres:
    restart: always
    image: postgres:latest
    networks:
      - backend
    ports:
      - "5454:5432"

  loader:
    build:
      context: ../lib/loader/
    volumes:
      - ../src/database:/tmp/database
    env_file: .env
    networks:
      - backend
    depends_on:
      - postgres

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ../src/api/lingany_api:/tmp/api/lingany_api
    env_file: .env
    command: bash -c "cd /tmp/api/lingany_api && /usr/local/bin/gunicorn -w 4 --reload -b :8080 app:app"

networks:
  backend:
