version: "3"
services:

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ../src/api/lingany_api:/tmp/api/lingany_api
    env_file: .env
    command: bash -c "cd /tmp/api/lingany_api && /usr/local/bin/gunicorn -w 4 -b :8080 app:app"

networks:
  backend:
